services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
      - /app/node_modules
      - /app/.next
      - /app/public
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    networks:
      - prometheus-net
    restart: unless-stopped

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
      - /app/__pycache__
    environment:
      - KRB5_KTNAME=/app/krb5.keytab
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - prometheus-net
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    volumes:
      - ../infrastructure/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - prometheus-net
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - prometheus-net
    ports:
      - "5050:80"
    depends_on:
      - postgres

  nginx:
    image: nginx:alpine
    volumes:
      - ../infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - prometheus-net
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"

volumes:
  postgres-data:


networks:
  prometheus-net:
    driver: bridge
