services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
      - /app/node_modules
      - /app/.next
      - /app/public
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - ENVIRONMENT=${ENVIRONMENT}
      - LOG_LEVEL=${LOG_LEVEL}
    networks:
      - prometheus-net
    restart: unless-stopped

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    hostname: ${KRB_HOST}
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
      - /app/__pycache__
      - ../krb5.keytab:/etc/krb5.keytab:ro
      - ../krb5.conf:/etc/krb5.conf:ro
    environment:
      - KRB5_KTNAME=${KRB_KTNAME}
      - KRB5_CONFIG=${KRB5_CONFIG}
      - KRB5_TRACE=${KRB5_TRACE}
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=${DATABASE_URL}
      - SERVICE_PRINCIPAL=${KRB_SERVICE}/${KRB_HOST}@${KRB_REALM}
      - ENVIRONMENT=${ENVIRONMENT}
      - LOG_LEVEL=${LOG_LEVEL}
      - LDAP_SERVER=${LDAP_SERVER}
      - LDAP_USER=${LDAP_USER}
      - LDAP_PASSWORD=${LDAP_PASSWORD}
    networks:
      - prometheus-net
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    volumes:
      - ../postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - prometheus-net
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - prometheus-net
    ports:
      - "5050:80"
    depends_on:
      - postgres

  nginx:
    build:
      context: ../nginx
      dockerfile: Dockerfile
    environment:
      - FRONTEND_HOST_NAME=${FRONTEND_HOST_NAME}
      - BACKEND_HOST_NAME=${BACKEND_HOST_NAME}
      - PGADMIN_HOST_NAME=${PGADMIN_HOST_NAME}
    depends_on:
      - frontend
      - backend
      - pgadmin
    ports:
      - "80:80"
    networks:
      - prometheus-net

volumes:
  postgres-data:

networks:
  prometheus-net:
    driver: bridge
